# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\x1a\x1bgoogle/protobuf/empty.proto\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"X\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x14\n\x0crelease_date\x18\x05 \x01(\t\";\n\x08Playlist\x12\x12\n\nid_usuario\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05songs\x18\x03 \x03(\x05\x32\xbb\x02\n\x0cMusicService\x12\x39\n\x0cListAllUsers\x12\x16.google.protobuf.Empty\x1a\x0f.streaming.User0\x01\x12\x39\n\x0cListAllSongs\x12\x16.google.protobuf.Empty\x1a\x0f.streaming.Song0\x01\x12;\n\x11ListUserPlaylists\x12\x0f.streaming.User\x1a\x13.streaming.Playlist0\x01\x12;\n\x11ListPlaylistSongs\x12\x13.streaming.Playlist\x1a\x0f.streaming.Song0\x01\x12;\n\x11ListSongPlaylists\x12\x0f.streaming.Song\x1a\x13.streaming.Playlist0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=59
  _globals['_USER']._serialized_end=91
  _globals['_SONG']._serialized_start=93
  _globals['_SONG']._serialized_end=181
  _globals['_PLAYLIST']._serialized_start=183
  _globals['_PLAYLIST']._serialized_end=242
  _globals['_MUSICSERVICE']._serialized_start=245
  _globals['_MUSICSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
