# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
# Protobuf Python Version: 3.17.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database
from google.protobuf import message as _message
from google.protobuf import descriptor_pb2 as descriptor__pb2
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12streaming.proto\x12\x08streaming\"\x1c\n\x0cUser\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06artist\x18\x03 \x01(\t\x12\x10\n\x08category\x18\x04 \x01(\t\x12\x14\n\x0crelease_date\x18\x05 \x01(\t\"\x1f\n\x08Playlist\x12\n\n\x02id_usuario\x18\x01 \x01(\x05\x12\n\n\x02nome\x18\x02 \x01(\t\x12\x0e\n\x06songs\x18\x03 \x03(\x05\")\n\x0bListAllUsers\x12\x0f\n\x07request\x18\x01 \x01(\x0b\x32\x08.User\x1a\x0e.User\"\x00\"\x0e\n\x0bListAllSongs\x12\x0f\n\x07request\x18\x01 \x01(\x0b\x32\x08.User\x1a\x0e.Song\"\x00\"\x12\n\x10ListUserPlaylists\x12\x0f\n\x07request\x18\x01 \x01(\x0b\x32\x08.User\x1a\x0e.Playlist\"\x00\"\x13\n\x11ListPlaylistSongs\x12\x0f\n\x07request\x18\x01 \x01(\x0b\x32\x08.Playlist\x1a\x0e.Song\"\x00\"\x12\n\x10ListSongPlaylists\x12\x0f\n\x07request\x18\x01 \x01(\x0b\x32\x08.Song\x1a\x0e.Playlist\"\x00')

class User(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class Song(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class Playlist(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class ListAllUsers(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class ListAllSongs(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class ListUserPlaylists(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class ListPlaylistSongs(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

class ListSongPlaylists(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = DESCRIPTOR

# @@protoc_insertion_point(module_scope)
